DPL-988 - Adds pacbio well association to aliquots
sanger/traction-service pull request #1181
Opened 2024-01-09 15:49 UTC by BenTopping

Closes #1152

#### Changes proposed in this pull request

- Adds PacBio Well association to aliquots

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-01-12 14:26 UTC, BenTopping commented on lib/tasks/migrate_pacbio_aliquot_data.rake
Do I need to test this file?

2024-01-16 10:27 UTC, stevieing requested changes
I think Aliquotable will need to be extended but we won't know yet. Everything is there just need some tests for the rake task.

2024-01-16 10:27 UTC, stevieing commented on lib/tasks/migrate_pacbio_aliquot_data.rake
I think we probably do need to test this file. We have had issues before where code has changed which has broken rake tasks.

2024-01-18 11:16 UTC, stevieing approved these changes

2024-01-18 11:34 UTC, BenTopping commented on app/models/concerns/aliquotable.rb
> +  def primary_aliquot
Changed in https://github.com/sanger/traction-service/pull/1189

2024-01-18 11:34 UTC, merged