DPL-990 - Modify pacbio libraries to support aliquots
sanger/traction-service pull request #1189
Opened 2024-01-18 11:33 UTC by BenTopping

Closes #1154

#### Changes proposed in this pull request

- Pacbio Libraries can have aliquots
- Rake task to migrate libraries to aliquots

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-01-30 17:06 UTC, stevieing requested changes
I have only set it to request changes to open a discussion rather than there being changes that need to be done. I think it would be good to try and centralise any behaviour related to aliquots wherever possible.

2024-01-31 11:55 UTC, BenTopping commented on app/models/pacbio/library.rb
> +    def create_used_aliquot
Yeah I think its possible after we implement aliquots for pools and wells. I dont want to create any premature aliquot data for them so I think it is safer to leave that in here for the time being. We also have libraries from pools to deal with for the time being so we need this 'if no pool' condition.

2024-01-31 11:58 UTC, BenTopping commented on lib/tasks/migrate_pacbio_aliquot_data.rake
> +      new_lib = library.dup
I suspect I was trying to test something and just abbreviated it quickly and left it. Will update.

2024-02-01 09:16 UTC, stevieing approved these changes

2024-02-13 10:37 UTC, closed without merging

2024-02-13 10:37 UTC, BenTopping commented
Close in favour of https://github.com/sanger/traction-service/pull/1219