Y24-073 - Populate PacBio run comments with pool barcode + concentration
sanger/traction-service pull request #1310
Opened 2024-05-08 12:53 UTC by SHIV5T3R

Closes #627 

#### Changes proposed in this pull request

- When a run is created, the barcode will have the format: "BARCODE CONCENTRATION". The same will happen when a run is updated as long as the comment is empty.

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-05-08 13:24 UTC, stevieing requested changes

2024-05-08 13:24 UTC, stevieing commented on app/models/pacbio/run.rb
> +          "#{well.smrt_link_options['library_concentration']}pM"
You can access library_concentration directly i.e `well.library_concentration`,

smrt_link_options are a store which provides accessors.

2024-05-08 15:17 UTC, stevieing approved these changes

2024-05-14 12:52 UTC, stevieing requested changes

2024-05-14 12:52 UTC, stevieing commented on app/models/pacbio/run.rb
> +    after_create :generate_name, :generate_comment
I think it might make sense to do this as a before_create so we don't have to do 2 saves. Sorry my fault didn't think aboout this.

2024-05-14 12:52 UTC, stevieing commented on app/models/pacbio/run.rb
> +    def generate_comment
I think you can simplify this. 

```
comment = wells.collect do |well|
        " #{well.used_aliquots.first.source.tube.barcode} #{well.library_concentration}pM"
      end.join(' ')

this.comments += comment
```

2024-05-14 12:52 UTC, stevieing commented on app/models/pacbio/run.rb
> +      comment = "#{comments} ".presence || ''
I am not sure you need to set comments to an emty string here as you are already doing this in comments accessor.

2024-05-15 12:47 UTC, SHIV5T3R commented
I've left the last line as `update(comments: (comments + comment)[0, 65535])` because the comment seems not be updating with this change. The splicing is for one of the tests. Because it's appending the new format, it'll be over the limit for the database itself and because of the way the run is created, the comment can't be spliced in the test. Not really sure how to go about this part.

2024-05-15 14:43 UTC, stevieing approved these changes

2024-05-20 12:57 UTC, merged