1179 dpl 1041 as a stakeholder james w i would traction to track pacbio smrtlink library types
sanger/traction-service pull request #1340
Opened 2024-06-11 10:45 UTC by stevieing

Closes #

#### Changes proposed in this pull request

- Add library type to smrt link options
- Add rake task to update library types
- Move smrt link options for well store to configuration

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-06-11 15:23 UTC, BenTopping commented on lib/tasks/update_smrt_link_option_library_type_for_revio.rake
Wondering if we can add this as part of the create_smrt_link_versions rake task so all existing records matching the smrt_link_version get the default when a new one is added? Would make future changes simpler as well.

2024-06-11 15:23 UTC, BenTopping commented on app/models/pacbio/well.rb
> +    store :smrt_link_options
Nice.

2024-06-12 07:33 UTC, stevieing commented on lib/tasks/update_smrt_link_option_library_type_for_revio.rake
Not entirely sure what you mean. If we run that task again I think it would just add the new option as it is already in there?

2024-06-12 08:00 UTC, BenTopping commented on lib/tasks/update_smrt_link_option_library_type_for_revio.rake
Yes it adds the new option but I was wondering whether the data should also be seeded there as well. So when we add a new option and then run `create_smrt_link_versions rake task` it would also set the default in the appropriate wells similar to how this rake task is currently doing it.
Saves us needing to do a separate seed rake task for the data whenever we add a new option.

2024-06-12 08:26 UTC, stevieing commented on lib/tasks/update_smrt_link_option_library_type_for_revio.rake
Ok. That makes sense.

2024-06-17 08:59 UTC, BenTopping requested changes

2024-06-17 08:59 UTC, BenTopping commented on lib/tasks/update_smrt_link_option_library_type_for_revio.rake
Can this be removed now?

2024-06-17 10:18 UTC, stevieing commented on lib/tasks/update_smrt_link_option_library_type_for_revio.rake
Yes. I had removed the tests which is why codecov is failing.

2024-06-17 10:20 UTC, BenTopping approved these changes

2024-06-17 14:33 UTC, BenTopping approved these changes

2024-06-18 07:20 UTC, BenTopping approved these changes

2024-06-18 08:50 UTC, merged