[WIP] Dpl 430 as developers we need to version the sample sheets so we can pin runs to different smrt link versions and make updating smrt link easier
sanger/traction-service pull request #786
Opened 2022-07-15 10:17 UTC by stevieing

Closes #

Changes proposed in this pull request:

*
*
* ...

2022-07-19 13:36 UTC, JamesGlover requested changes

2022-07-19 13:43 UTC, stevieing commented on db/migrate/20220714125848_add_smrt_link_version_to_pacbio_run.rb
> +    add_column :pacbio_runs, :smrt_link_version, :string, null: false
Not sure. I have created a rails task to update the existing records. Happy to run the task when it gets deployed.

2022-07-19 13:45 UTC, stevieing commented on app/models/pacbio/run.rb
> +      Pipelines.pacbio.sample_sheet.send(smrt_link_version)
If we provide it as a drop down in the front end would that not negate this issue? We would have to do that anyway as the run form would depend on it.

2022-07-21 12:56 UTC, JamesGlover commented on app/models/pacbio/run.rb
> +      Pipelines.pacbio.sample_sheet.send(smrt_link_version)
It would protect against user error, but not maliciousness.

2022-07-27 10:49 UTC, JamesGlover approved these changes

2022-07-27 10:50 UTC, merged